baseURL = "http://example.org/"
languageCode = "en-us"
theme = "hyde"
title = "My New Hugo Site"
[[menu.main]]
name = "Github"
url = "http://github.com"
weight = 2
[params]
layoutReverse = false
themeColor = ""
